/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 23
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  anon_sym_LT = 3,
  anon_sym_GT = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_STAR = 9,
  anon_sym_SLASH = 10,
  anon_sym_PERCENT = 11,
  anon_sym_COLON = 12,
  anon_sym_AT = 13,
  anon_sym_BANG = 14,
  anon_sym_QMARK = 15,
  sym_stack_separator = 16,
  sym_choice_separator = 17,
  sym_group_separator = 18,
  sym_range = 19,
  anon_sym_TILDE = 20,
  anon_sym_DASH = 21,
  sym_elongation = 22,
  sym_number = 23,
  sym_note = 24,
  sym_word = 25,
  sym_source = 26,
  sym__item = 27,
  sym_subsequence = 28,
  sym_alternation = 29,
  sym_polymeter = 30,
  sym_euclid = 31,
  sym_modifier = 32,
  sym_rest = 33,
  aux_sym_source_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_COLON] = ":",
  [anon_sym_AT] = "@",
  [anon_sym_BANG] = "!",
  [anon_sym_QMARK] = "\?",
  [sym_stack_separator] = "stack_separator",
  [sym_choice_separator] = "choice_separator",
  [sym_group_separator] = "group_separator",
  [sym_range] = "range",
  [anon_sym_TILDE] = "~",
  [anon_sym_DASH] = "-",
  [sym_elongation] = "elongation",
  [sym_number] = "number",
  [sym_note] = "note",
  [sym_word] = "word",
  [sym_source] = "source",
  [sym__item] = "_item",
  [sym_subsequence] = "subsequence",
  [sym_alternation] = "alternation",
  [sym_polymeter] = "polymeter",
  [sym_euclid] = "euclid",
  [sym_modifier] = "modifier",
  [sym_rest] = "rest",
  [aux_sym_source_repeat1] = "source_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [sym_stack_separator] = sym_stack_separator,
  [sym_choice_separator] = sym_choice_separator,
  [sym_group_separator] = sym_group_separator,
  [sym_range] = sym_range,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_elongation] = sym_elongation,
  [sym_number] = sym_number,
  [sym_note] = sym_note,
  [sym_word] = sym_word,
  [sym_source] = sym_source,
  [sym__item] = sym__item,
  [sym_subsequence] = sym_subsequence,
  [sym_alternation] = sym_alternation,
  [sym_polymeter] = sym_polymeter,
  [sym_euclid] = sym_euclid,
  [sym_modifier] = sym_modifier,
  [sym_rest] = sym_rest,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [sym_stack_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_choice_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_group_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_elongation] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_note] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_subsequence] = {
    .visible = true,
    .named = true,
  },
  [sym_alternation] = {
    .visible = true,
    .named = true,
  },
  [sym_polymeter] = {
    .visible = true,
    .named = true,
  },
  [sym_euclid] = {
    .visible = true,
    .named = true,
  },
  [sym_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_rest] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_operator = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_operator] = "operator",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operator, 0},
  [1] =
    {field_operator, 0},
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '!', 18,
        '%', 15,
        '(', 11,
        ')', 12,
        '*', 13,
        ',', 20,
        '-', 25,
        '.', 22,
        '/', 14,
        ':', 16,
        '<', 7,
        '>', 8,
        '?', 19,
        '@', 17,
        '[', 5,
        ']', 6,
        '_', 26,
        '{', 9,
        '|', 21,
        '}', 10,
        '~', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'G') ||
          ('a' <= lookahead && lookahead <= 'g')) ADVANCE(29);
      if (('H' <= lookahead && lookahead <= 'Z') ||
          ('h' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == '<') ADVANCE(7);
      if (lookahead == '[') ADVANCE(5);
      if (lookahead == '{') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'G') ||
          ('a' <= lookahead && lookahead <= 'g')) ADVANCE(29);
      if (('H' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('h' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_stack_separator);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_choice_separator);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_group_separator);
      if (lookahead == '.') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_range);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '.') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_elongation);
      if (lookahead == '#' ||
          lookahead == '\'' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_note);
      if (lookahead == '#' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 's') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead == '\'' ||
          lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_note);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead == '#' ||
          lookahead == '\'' ||
          lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '#' ||
          lookahead == '\'' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [sym_stack_separator] = ACTIONS(1),
    [sym_choice_separator] = ACTIONS(1),
    [sym_group_separator] = ACTIONS(1),
    [sym_range] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_elongation] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_note] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(24),
    [sym__item] = STATE(7),
    [sym_subsequence] = STATE(7),
    [sym_alternation] = STATE(7),
    [sym_polymeter] = STATE(7),
    [sym_euclid] = STATE(7),
    [sym_modifier] = STATE(7),
    [sym_rest] = STATE(7),
    [aux_sym_source_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_QMARK] = ACTIONS(15),
    [sym_stack_separator] = ACTIONS(17),
    [sym_choice_separator] = ACTIONS(17),
    [sym_group_separator] = ACTIONS(19),
    [sym_range] = ACTIONS(17),
    [anon_sym_TILDE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_elongation] = ACTIONS(19),
    [sym_number] = ACTIONS(17),
    [sym_note] = ACTIONS(19),
    [sym_word] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym__item] = STATE(2),
    [sym_subsequence] = STATE(2),
    [sym_alternation] = STATE(2),
    [sym_polymeter] = STATE(2),
    [sym_euclid] = STATE(2),
    [sym_modifier] = STATE(2),
    [sym_rest] = STATE(2),
    [aux_sym_source_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(25),
    [anon_sym_LT] = ACTIONS(30),
    [anon_sym_GT] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(36),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(39),
    [anon_sym_COLON] = ACTIONS(39),
    [anon_sym_AT] = ACTIONS(42),
    [anon_sym_BANG] = ACTIONS(42),
    [anon_sym_QMARK] = ACTIONS(42),
    [sym_stack_separator] = ACTIONS(45),
    [sym_choice_separator] = ACTIONS(45),
    [sym_group_separator] = ACTIONS(48),
    [sym_range] = ACTIONS(45),
    [anon_sym_TILDE] = ACTIONS(51),
    [anon_sym_DASH] = ACTIONS(54),
    [sym_elongation] = ACTIONS(48),
    [sym_number] = ACTIONS(45),
    [sym_note] = ACTIONS(48),
    [sym_word] = ACTIONS(48),
  },
  [STATE(3)] = {
    [sym__item] = STATE(8),
    [sym_subsequence] = STATE(8),
    [sym_alternation] = STATE(8),
    [sym_polymeter] = STATE(8),
    [sym_euclid] = STATE(8),
    [sym_modifier] = STATE(8),
    [sym_rest] = STATE(8),
    [aux_sym_source_repeat1] = STATE(8),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_RBRACK] = ACTIONS(57),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_QMARK] = ACTIONS(15),
    [sym_stack_separator] = ACTIONS(59),
    [sym_choice_separator] = ACTIONS(59),
    [sym_group_separator] = ACTIONS(61),
    [sym_range] = ACTIONS(59),
    [anon_sym_TILDE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_elongation] = ACTIONS(61),
    [sym_number] = ACTIONS(59),
    [sym_note] = ACTIONS(61),
    [sym_word] = ACTIONS(61),
  },
  [STATE(4)] = {
    [sym__item] = STATE(9),
    [sym_subsequence] = STATE(9),
    [sym_alternation] = STATE(9),
    [sym_polymeter] = STATE(9),
    [sym_euclid] = STATE(9),
    [sym_modifier] = STATE(9),
    [sym_rest] = STATE(9),
    [aux_sym_source_repeat1] = STATE(9),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_GT] = ACTIONS(63),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_QMARK] = ACTIONS(15),
    [sym_stack_separator] = ACTIONS(65),
    [sym_choice_separator] = ACTIONS(65),
    [sym_group_separator] = ACTIONS(67),
    [sym_range] = ACTIONS(65),
    [anon_sym_TILDE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_elongation] = ACTIONS(67),
    [sym_number] = ACTIONS(65),
    [sym_note] = ACTIONS(67),
    [sym_word] = ACTIONS(67),
  },
  [STATE(5)] = {
    [sym__item] = STATE(10),
    [sym_subsequence] = STATE(10),
    [sym_alternation] = STATE(10),
    [sym_polymeter] = STATE(10),
    [sym_euclid] = STATE(10),
    [sym_modifier] = STATE(10),
    [sym_rest] = STATE(10),
    [aux_sym_source_repeat1] = STATE(10),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(69),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_QMARK] = ACTIONS(15),
    [sym_stack_separator] = ACTIONS(71),
    [sym_choice_separator] = ACTIONS(71),
    [sym_group_separator] = ACTIONS(73),
    [sym_range] = ACTIONS(71),
    [anon_sym_TILDE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_elongation] = ACTIONS(73),
    [sym_number] = ACTIONS(71),
    [sym_note] = ACTIONS(73),
    [sym_word] = ACTIONS(73),
  },
  [STATE(6)] = {
    [sym__item] = STATE(11),
    [sym_subsequence] = STATE(11),
    [sym_alternation] = STATE(11),
    [sym_polymeter] = STATE(11),
    [sym_euclid] = STATE(11),
    [sym_modifier] = STATE(11),
    [sym_rest] = STATE(11),
    [aux_sym_source_repeat1] = STATE(11),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(75),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_QMARK] = ACTIONS(15),
    [sym_stack_separator] = ACTIONS(77),
    [sym_choice_separator] = ACTIONS(77),
    [sym_group_separator] = ACTIONS(79),
    [sym_range] = ACTIONS(77),
    [anon_sym_TILDE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_elongation] = ACTIONS(79),
    [sym_number] = ACTIONS(77),
    [sym_note] = ACTIONS(79),
    [sym_word] = ACTIONS(79),
  },
  [STATE(7)] = {
    [sym__item] = STATE(2),
    [sym_subsequence] = STATE(2),
    [sym_alternation] = STATE(2),
    [sym_polymeter] = STATE(2),
    [sym_euclid] = STATE(2),
    [sym_modifier] = STATE(2),
    [sym_rest] = STATE(2),
    [aux_sym_source_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_QMARK] = ACTIONS(15),
    [sym_stack_separator] = ACTIONS(83),
    [sym_choice_separator] = ACTIONS(83),
    [sym_group_separator] = ACTIONS(85),
    [sym_range] = ACTIONS(83),
    [anon_sym_TILDE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_elongation] = ACTIONS(85),
    [sym_number] = ACTIONS(83),
    [sym_note] = ACTIONS(85),
    [sym_word] = ACTIONS(85),
  },
  [STATE(8)] = {
    [sym__item] = STATE(2),
    [sym_subsequence] = STATE(2),
    [sym_alternation] = STATE(2),
    [sym_polymeter] = STATE(2),
    [sym_euclid] = STATE(2),
    [sym_modifier] = STATE(2),
    [sym_rest] = STATE(2),
    [aux_sym_source_repeat1] = STATE(2),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_RBRACK] = ACTIONS(87),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_QMARK] = ACTIONS(15),
    [sym_stack_separator] = ACTIONS(83),
    [sym_choice_separator] = ACTIONS(83),
    [sym_group_separator] = ACTIONS(85),
    [sym_range] = ACTIONS(83),
    [anon_sym_TILDE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_elongation] = ACTIONS(85),
    [sym_number] = ACTIONS(83),
    [sym_note] = ACTIONS(85),
    [sym_word] = ACTIONS(85),
  },
  [STATE(9)] = {
    [sym__item] = STATE(2),
    [sym_subsequence] = STATE(2),
    [sym_alternation] = STATE(2),
    [sym_polymeter] = STATE(2),
    [sym_euclid] = STATE(2),
    [sym_modifier] = STATE(2),
    [sym_rest] = STATE(2),
    [aux_sym_source_repeat1] = STATE(2),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_GT] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_QMARK] = ACTIONS(15),
    [sym_stack_separator] = ACTIONS(83),
    [sym_choice_separator] = ACTIONS(83),
    [sym_group_separator] = ACTIONS(85),
    [sym_range] = ACTIONS(83),
    [anon_sym_TILDE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_elongation] = ACTIONS(85),
    [sym_number] = ACTIONS(83),
    [sym_note] = ACTIONS(85),
    [sym_word] = ACTIONS(85),
  },
  [STATE(10)] = {
    [sym__item] = STATE(2),
    [sym_subsequence] = STATE(2),
    [sym_alternation] = STATE(2),
    [sym_polymeter] = STATE(2),
    [sym_euclid] = STATE(2),
    [sym_modifier] = STATE(2),
    [sym_rest] = STATE(2),
    [aux_sym_source_repeat1] = STATE(2),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(91),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_QMARK] = ACTIONS(15),
    [sym_stack_separator] = ACTIONS(83),
    [sym_choice_separator] = ACTIONS(83),
    [sym_group_separator] = ACTIONS(85),
    [sym_range] = ACTIONS(83),
    [anon_sym_TILDE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_elongation] = ACTIONS(85),
    [sym_number] = ACTIONS(83),
    [sym_note] = ACTIONS(85),
    [sym_word] = ACTIONS(85),
  },
  [STATE(11)] = {
    [sym__item] = STATE(2),
    [sym_subsequence] = STATE(2),
    [sym_alternation] = STATE(2),
    [sym_polymeter] = STATE(2),
    [sym_euclid] = STATE(2),
    [sym_modifier] = STATE(2),
    [sym_rest] = STATE(2),
    [aux_sym_source_repeat1] = STATE(2),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(93),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_QMARK] = ACTIONS(15),
    [sym_stack_separator] = ACTIONS(83),
    [sym_choice_separator] = ACTIONS(83),
    [sym_group_separator] = ACTIONS(85),
    [sym_range] = ACTIONS(83),
    [anon_sym_TILDE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_elongation] = ACTIONS(85),
    [sym_number] = ACTIONS(83),
    [sym_note] = ACTIONS(85),
    [sym_word] = ACTIONS(85),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(95),
    [anon_sym_LBRACK] = ACTIONS(95),
    [anon_sym_RBRACK] = ACTIONS(95),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_GT] = ACTIONS(95),
    [anon_sym_LBRACE] = ACTIONS(95),
    [anon_sym_RBRACE] = ACTIONS(95),
    [anon_sym_LPAREN] = ACTIONS(95),
    [anon_sym_RPAREN] = ACTIONS(95),
    [anon_sym_STAR] = ACTIONS(95),
    [anon_sym_SLASH] = ACTIONS(95),
    [anon_sym_PERCENT] = ACTIONS(95),
    [anon_sym_COLON] = ACTIONS(95),
    [anon_sym_AT] = ACTIONS(95),
    [anon_sym_BANG] = ACTIONS(95),
    [anon_sym_QMARK] = ACTIONS(95),
    [sym_stack_separator] = ACTIONS(95),
    [sym_choice_separator] = ACTIONS(95),
    [sym_group_separator] = ACTIONS(97),
    [sym_range] = ACTIONS(95),
    [anon_sym_TILDE] = ACTIONS(95),
    [anon_sym_DASH] = ACTIONS(97),
    [sym_elongation] = ACTIONS(97),
    [sym_number] = ACTIONS(95),
    [sym_note] = ACTIONS(97),
    [sym_word] = ACTIONS(97),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(99),
    [anon_sym_LBRACK] = ACTIONS(99),
    [anon_sym_RBRACK] = ACTIONS(99),
    [anon_sym_LT] = ACTIONS(99),
    [anon_sym_GT] = ACTIONS(99),
    [anon_sym_LBRACE] = ACTIONS(99),
    [anon_sym_RBRACE] = ACTIONS(99),
    [anon_sym_LPAREN] = ACTIONS(99),
    [anon_sym_RPAREN] = ACTIONS(99),
    [anon_sym_STAR] = ACTIONS(99),
    [anon_sym_SLASH] = ACTIONS(99),
    [anon_sym_PERCENT] = ACTIONS(99),
    [anon_sym_COLON] = ACTIONS(99),
    [anon_sym_AT] = ACTIONS(99),
    [anon_sym_BANG] = ACTIONS(99),
    [anon_sym_QMARK] = ACTIONS(99),
    [sym_stack_separator] = ACTIONS(99),
    [sym_choice_separator] = ACTIONS(99),
    [sym_group_separator] = ACTIONS(101),
    [sym_range] = ACTIONS(99),
    [anon_sym_TILDE] = ACTIONS(99),
    [anon_sym_DASH] = ACTIONS(101),
    [sym_elongation] = ACTIONS(101),
    [sym_number] = ACTIONS(103),
    [sym_note] = ACTIONS(101),
    [sym_word] = ACTIONS(101),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(105),
    [anon_sym_LBRACK] = ACTIONS(105),
    [anon_sym_RBRACK] = ACTIONS(105),
    [anon_sym_LT] = ACTIONS(105),
    [anon_sym_GT] = ACTIONS(105),
    [anon_sym_LBRACE] = ACTIONS(105),
    [anon_sym_RBRACE] = ACTIONS(105),
    [anon_sym_LPAREN] = ACTIONS(105),
    [anon_sym_RPAREN] = ACTIONS(105),
    [anon_sym_STAR] = ACTIONS(105),
    [anon_sym_SLASH] = ACTIONS(105),
    [anon_sym_PERCENT] = ACTIONS(105),
    [anon_sym_COLON] = ACTIONS(105),
    [anon_sym_AT] = ACTIONS(105),
    [anon_sym_BANG] = ACTIONS(105),
    [anon_sym_QMARK] = ACTIONS(105),
    [sym_stack_separator] = ACTIONS(105),
    [sym_choice_separator] = ACTIONS(105),
    [sym_group_separator] = ACTIONS(107),
    [sym_range] = ACTIONS(105),
    [anon_sym_TILDE] = ACTIONS(105),
    [anon_sym_DASH] = ACTIONS(107),
    [sym_elongation] = ACTIONS(107),
    [sym_number] = ACTIONS(105),
    [sym_note] = ACTIONS(107),
    [sym_word] = ACTIONS(107),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(109),
    [anon_sym_LBRACK] = ACTIONS(109),
    [anon_sym_RBRACK] = ACTIONS(109),
    [anon_sym_LT] = ACTIONS(109),
    [anon_sym_GT] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(109),
    [anon_sym_RBRACE] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(109),
    [anon_sym_RPAREN] = ACTIONS(109),
    [anon_sym_STAR] = ACTIONS(109),
    [anon_sym_SLASH] = ACTIONS(109),
    [anon_sym_PERCENT] = ACTIONS(109),
    [anon_sym_COLON] = ACTIONS(109),
    [anon_sym_AT] = ACTIONS(109),
    [anon_sym_BANG] = ACTIONS(109),
    [anon_sym_QMARK] = ACTIONS(109),
    [sym_stack_separator] = ACTIONS(109),
    [sym_choice_separator] = ACTIONS(109),
    [sym_group_separator] = ACTIONS(111),
    [sym_range] = ACTIONS(109),
    [anon_sym_TILDE] = ACTIONS(109),
    [anon_sym_DASH] = ACTIONS(111),
    [sym_elongation] = ACTIONS(111),
    [sym_number] = ACTIONS(109),
    [sym_note] = ACTIONS(111),
    [sym_word] = ACTIONS(111),
  },
  [STATE(16)] = {
    [ts_builtin_sym_end] = ACTIONS(113),
    [anon_sym_LBRACK] = ACTIONS(113),
    [anon_sym_RBRACK] = ACTIONS(113),
    [anon_sym_LT] = ACTIONS(113),
    [anon_sym_GT] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(113),
    [anon_sym_RBRACE] = ACTIONS(113),
    [anon_sym_LPAREN] = ACTIONS(113),
    [anon_sym_RPAREN] = ACTIONS(113),
    [anon_sym_STAR] = ACTIONS(113),
    [anon_sym_SLASH] = ACTIONS(113),
    [anon_sym_PERCENT] = ACTIONS(113),
    [anon_sym_COLON] = ACTIONS(113),
    [anon_sym_AT] = ACTIONS(113),
    [anon_sym_BANG] = ACTIONS(113),
    [anon_sym_QMARK] = ACTIONS(113),
    [sym_stack_separator] = ACTIONS(113),
    [sym_choice_separator] = ACTIONS(113),
    [sym_group_separator] = ACTIONS(115),
    [sym_range] = ACTIONS(113),
    [anon_sym_TILDE] = ACTIONS(113),
    [anon_sym_DASH] = ACTIONS(115),
    [sym_elongation] = ACTIONS(115),
    [sym_number] = ACTIONS(113),
    [sym_note] = ACTIONS(115),
    [sym_word] = ACTIONS(115),
  },
  [STATE(17)] = {
    [ts_builtin_sym_end] = ACTIONS(117),
    [anon_sym_LBRACK] = ACTIONS(117),
    [anon_sym_RBRACK] = ACTIONS(117),
    [anon_sym_LT] = ACTIONS(117),
    [anon_sym_GT] = ACTIONS(117),
    [anon_sym_LBRACE] = ACTIONS(117),
    [anon_sym_RBRACE] = ACTIONS(117),
    [anon_sym_LPAREN] = ACTIONS(117),
    [anon_sym_RPAREN] = ACTIONS(117),
    [anon_sym_STAR] = ACTIONS(117),
    [anon_sym_SLASH] = ACTIONS(117),
    [anon_sym_PERCENT] = ACTIONS(117),
    [anon_sym_COLON] = ACTIONS(117),
    [anon_sym_AT] = ACTIONS(117),
    [anon_sym_BANG] = ACTIONS(117),
    [anon_sym_QMARK] = ACTIONS(117),
    [sym_stack_separator] = ACTIONS(117),
    [sym_choice_separator] = ACTIONS(117),
    [sym_group_separator] = ACTIONS(119),
    [sym_range] = ACTIONS(117),
    [anon_sym_TILDE] = ACTIONS(117),
    [anon_sym_DASH] = ACTIONS(119),
    [sym_elongation] = ACTIONS(119),
    [sym_number] = ACTIONS(117),
    [sym_note] = ACTIONS(119),
    [sym_word] = ACTIONS(119),
  },
  [STATE(18)] = {
    [ts_builtin_sym_end] = ACTIONS(121),
    [anon_sym_LBRACK] = ACTIONS(121),
    [anon_sym_RBRACK] = ACTIONS(121),
    [anon_sym_LT] = ACTIONS(121),
    [anon_sym_GT] = ACTIONS(121),
    [anon_sym_LBRACE] = ACTIONS(121),
    [anon_sym_RBRACE] = ACTIONS(121),
    [anon_sym_LPAREN] = ACTIONS(121),
    [anon_sym_RPAREN] = ACTIONS(121),
    [anon_sym_STAR] = ACTIONS(121),
    [anon_sym_SLASH] = ACTIONS(121),
    [anon_sym_PERCENT] = ACTIONS(121),
    [anon_sym_COLON] = ACTIONS(121),
    [anon_sym_AT] = ACTIONS(121),
    [anon_sym_BANG] = ACTIONS(121),
    [anon_sym_QMARK] = ACTIONS(121),
    [sym_stack_separator] = ACTIONS(121),
    [sym_choice_separator] = ACTIONS(121),
    [sym_group_separator] = ACTIONS(123),
    [sym_range] = ACTIONS(121),
    [anon_sym_TILDE] = ACTIONS(121),
    [anon_sym_DASH] = ACTIONS(123),
    [sym_elongation] = ACTIONS(123),
    [sym_number] = ACTIONS(121),
    [sym_note] = ACTIONS(123),
    [sym_word] = ACTIONS(123),
  },
  [STATE(19)] = {
    [ts_builtin_sym_end] = ACTIONS(125),
    [anon_sym_LBRACK] = ACTIONS(125),
    [anon_sym_RBRACK] = ACTIONS(125),
    [anon_sym_LT] = ACTIONS(125),
    [anon_sym_GT] = ACTIONS(125),
    [anon_sym_LBRACE] = ACTIONS(125),
    [anon_sym_RBRACE] = ACTIONS(125),
    [anon_sym_LPAREN] = ACTIONS(125),
    [anon_sym_RPAREN] = ACTIONS(125),
    [anon_sym_STAR] = ACTIONS(125),
    [anon_sym_SLASH] = ACTIONS(125),
    [anon_sym_PERCENT] = ACTIONS(125),
    [anon_sym_COLON] = ACTIONS(125),
    [anon_sym_AT] = ACTIONS(125),
    [anon_sym_BANG] = ACTIONS(125),
    [anon_sym_QMARK] = ACTIONS(125),
    [sym_stack_separator] = ACTIONS(125),
    [sym_choice_separator] = ACTIONS(125),
    [sym_group_separator] = ACTIONS(127),
    [sym_range] = ACTIONS(125),
    [anon_sym_TILDE] = ACTIONS(125),
    [anon_sym_DASH] = ACTIONS(127),
    [sym_elongation] = ACTIONS(127),
    [sym_number] = ACTIONS(125),
    [sym_note] = ACTIONS(127),
    [sym_word] = ACTIONS(127),
  },
  [STATE(20)] = {
    [ts_builtin_sym_end] = ACTIONS(129),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_RBRACK] = ACTIONS(129),
    [anon_sym_LT] = ACTIONS(129),
    [anon_sym_GT] = ACTIONS(129),
    [anon_sym_LBRACE] = ACTIONS(129),
    [anon_sym_RBRACE] = ACTIONS(129),
    [anon_sym_LPAREN] = ACTIONS(129),
    [anon_sym_RPAREN] = ACTIONS(129),
    [anon_sym_STAR] = ACTIONS(129),
    [anon_sym_SLASH] = ACTIONS(129),
    [anon_sym_PERCENT] = ACTIONS(129),
    [anon_sym_COLON] = ACTIONS(129),
    [anon_sym_AT] = ACTIONS(129),
    [anon_sym_BANG] = ACTIONS(129),
    [anon_sym_QMARK] = ACTIONS(129),
    [sym_stack_separator] = ACTIONS(129),
    [sym_choice_separator] = ACTIONS(129),
    [sym_group_separator] = ACTIONS(131),
    [sym_range] = ACTIONS(129),
    [anon_sym_TILDE] = ACTIONS(129),
    [anon_sym_DASH] = ACTIONS(131),
    [sym_elongation] = ACTIONS(131),
    [sym_number] = ACTIONS(129),
    [sym_note] = ACTIONS(131),
    [sym_word] = ACTIONS(131),
  },
  [STATE(21)] = {
    [ts_builtin_sym_end] = ACTIONS(133),
    [anon_sym_LBRACK] = ACTIONS(133),
    [anon_sym_RBRACK] = ACTIONS(133),
    [anon_sym_LT] = ACTIONS(133),
    [anon_sym_GT] = ACTIONS(133),
    [anon_sym_LBRACE] = ACTIONS(133),
    [anon_sym_RBRACE] = ACTIONS(133),
    [anon_sym_LPAREN] = ACTIONS(133),
    [anon_sym_RPAREN] = ACTIONS(133),
    [anon_sym_STAR] = ACTIONS(133),
    [anon_sym_SLASH] = ACTIONS(133),
    [anon_sym_PERCENT] = ACTIONS(133),
    [anon_sym_COLON] = ACTIONS(133),
    [anon_sym_AT] = ACTIONS(133),
    [anon_sym_BANG] = ACTIONS(133),
    [anon_sym_QMARK] = ACTIONS(133),
    [sym_stack_separator] = ACTIONS(133),
    [sym_choice_separator] = ACTIONS(133),
    [sym_group_separator] = ACTIONS(135),
    [sym_range] = ACTIONS(133),
    [anon_sym_TILDE] = ACTIONS(133),
    [anon_sym_DASH] = ACTIONS(135),
    [sym_elongation] = ACTIONS(135),
    [sym_number] = ACTIONS(133),
    [sym_note] = ACTIONS(135),
    [sym_word] = ACTIONS(135),
  },
  [STATE(22)] = {
    [ts_builtin_sym_end] = ACTIONS(137),
    [anon_sym_LBRACK] = ACTIONS(137),
    [anon_sym_RBRACK] = ACTIONS(137),
    [anon_sym_LT] = ACTIONS(137),
    [anon_sym_GT] = ACTIONS(137),
    [anon_sym_LBRACE] = ACTIONS(137),
    [anon_sym_RBRACE] = ACTIONS(137),
    [anon_sym_LPAREN] = ACTIONS(137),
    [anon_sym_RPAREN] = ACTIONS(137),
    [anon_sym_STAR] = ACTIONS(137),
    [anon_sym_SLASH] = ACTIONS(137),
    [anon_sym_PERCENT] = ACTIONS(137),
    [anon_sym_COLON] = ACTIONS(137),
    [anon_sym_AT] = ACTIONS(137),
    [anon_sym_BANG] = ACTIONS(137),
    [anon_sym_QMARK] = ACTIONS(137),
    [sym_stack_separator] = ACTIONS(137),
    [sym_choice_separator] = ACTIONS(137),
    [sym_group_separator] = ACTIONS(139),
    [sym_range] = ACTIONS(137),
    [anon_sym_TILDE] = ACTIONS(137),
    [anon_sym_DASH] = ACTIONS(139),
    [sym_elongation] = ACTIONS(139),
    [sym_number] = ACTIONS(137),
    [sym_note] = ACTIONS(139),
    [sym_word] = ACTIONS(139),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      sym_number,
    ACTIONS(141), 2,
      sym_note,
      sym_word,
    STATE(18), 3,
      sym_subsequence,
      sym_alternation,
      sym_polymeter,
  [22] = 1,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(23)] = 0,
  [SMALL_STATE(24)] = 22,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rest, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rest, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modifier, 1, 0, 1),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_modifier, 1, 0, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subsequence, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subsequence, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_polymeter, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_polymeter, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternation, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alternation, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_euclid, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_euclid, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modifier, 2, 0, 2),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_modifier, 2, 0, 2),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subsequence, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subsequence, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternation, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alternation, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_polymeter, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_polymeter, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_euclid, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_euclid, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [143] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_strudel_mini(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "strudel_mini",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
